#security:
#  jwt:
#    client:
#      clientId: activity-microservice
#      clientSecret: nextdefault
#      accessTokenUri: http://127.0.0.1:8084/auth/auth/inn
#      grant-type: client_credentials
#      scope: server

server:
  servlet:
    context-path: /activity
  port: 8085

spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: activity
      port: 27017